# Generated by Django 2.0.7 on 2018-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('G', '일반유저'), ('F', '페이스북 유저')], default='G', max_length=1),
        ),
    ]
