# Generated by Django 2.0.6 on 2018-07-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180629_0614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('from_user', 'to_user', 'relation_type')},
        ),
    ]
